### ISSUE TITLE
Application closes before CommandLineArgs get sent

### ISSUE THREAD

**Issue by henbagle** [soheilkd/SingleInstanceCore#4] opened 2021-05-19 20:32 UTC
We're having a problem where OnInstanceInvoked isn't getting triggered. I cloned the code and debugged it locally, and it seems like the message bus was being disposed of before it finished sending the command line arguments to the first instance. Adding a short Thread.Sleep() before calling Cleanup() solved the problem temporarily.

Our application pretty much matches the example code.

This problem occurred on 2.0, though I believe it was also present on 1.0 as we upgraded to try and see if it would fix the problem.

**Comment by soheilkd** [comment] 2021-05-24 16:09
I couldn't reproduce that on my own system.

I've added Wait() to message publishing method, so it should ensure that the publishing is finished before getting to next method in your code (which is closing the app apparently, and/or calling Cleanup()). 

But I cannot be sure that fixes it in your case as I couldn't reproduce that in the first place. So would you try building and trying 'FixIssue4' branch?

**Comment by henbagle** [comment] 2021-05-25 01:37
That fixes the problem. Thank you for your help!

**Comment by henbagle** [comment] 2021-05-25 01:38
That fixes the problem. Thank you for your help!

**Closed** 2021-05-25 06:35 UTC
